### ISSUE TITLE
LLC4320.ipynb error

### ISSUE THREAD

**Issue by ThomasHaine** [MaceKuailv/seaduck_sciserver_notebook#2]
Computing the trajectories on SciServer at cell [9] errors:

<img width="1800" alt="image" src="https://github.com/MaceKuailv/seaduck_sciserver_notebook/assets/44037162/5e2b1379-2ac9-4ad8-9900-1f517194a400">

**Comment by MaceKuailv** [comment]
OK, this is a very computationally expensive sanity check that I thought I commented out...It turns out I didn't use the latest code to run the notebook...

In conclusion, this is a good check. Something has gone wrong here. This error suggests that some points are out of the cell when it starts.

**Comment by MaceKuailv** [comment]
resolved by https://github.com/MaceKuailv/seaduck/pull/62. 

I am running all the notebooks with the updated code (with the checks that raised that error as well as a few more checks).

Will be closed in a second after running the notebooks and pull request.

**Comment by MaceKuailv** [comment]
@ThomasHaine has ran the notebook in PR #5. close as resolved
